---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.8.0

executors:
  # Whenever the Go version is updated here, .promu.yml should also be updated.
  golang:
    docker:
      - image: circleci/golang:1.14
  golang_jenkins:
    docker:
      - image: circleci/golang:1.14

workflows:
  version: 2
  jenkins_exporter:
    jobs:
      - prometheus/build:
          name: build
          filters:
            tags:
              only: /.*/
      - prometheus/publish_master:
          context: org-context
          requires:
            - build
          filters:
            branches:
              only: master
      - prometheus/publish_release:
          context: org-context
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
